apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: sportapps-ns
  labels:
    app: user
  annotations:
    cloud.google.com/load-balancer-neg-ready: '{"ingress": false}'
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: sportapps-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 60
  - type: Resource
    resource:
     name: memory
     target:
       type: Utilization
       averageValue: 800Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: sportapps-ns
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccountName: sportapps-service-account
      automountServiceAccountToken: true    
      containers:
        - name: user
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.7Gi
          livenessProbe:
            httpGet:
              path: /api/liveness/health-check
              scheme: HTTP
              port: 3000
            initialDelaySeconds: 60
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/liveness/health-check
              scheme: HTTP
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: db_password
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: jwt_secret
                  optional: false
      tolerations:
      - key: instance_type
        value: spot
        effect: NoSchedule
        operator: Equal

---

apiVersion: v1
kind: ConfigMap
data:
  host: 'database'
  port: '5432'
  name: 'postgres'
  username: 'postgres'

metadata:
  name: user-config
  namespace: sportapps-ns
  labels:
    app: users

---

apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: sportapps-ns
type: Opaque
data:
  db_password: NG0jUllSUz1wJUEoans6Ig==
  jwt_secret: c2VjcmV0

---

apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: sportapps-ns
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      protocol: TCP

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: database-hpa
  namespace: sportapps-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 60
  - type: Resource
    resource:
     name: memory
     target:
       type: Utilization
       averageValue: 800Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: sportapps-ns
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      serviceAccountName: sportapps-service-account
      automountServiceAccountToken: true
      containers:
        - name: database
          image: postgres:14.3
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.7Gi
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: db_password
                  optional: false
      tolerations:
      - key: instance_type
        value: spot
        effect: NoSchedule
        operator: Equal